# Generated by Django 5.0.2 on 2024-05-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
