# Generated by Django 5.0.2 on 2024-05-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_likes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='minute',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='second',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
